#!/bin/bash
 
# Invoke the Forever module (to START our Node.js server).
PORT=3456 \
ASSET_FILES_VERSION=107 \
forever \
start \
--minUptime 1 \
-l forever.log \
-a \
-o out.log \
-e err.log \
app.js \
